### ISSUE TITLE
UX Improvement - Reduce scrolling

### ISSUE THREAD

**Issue by hXtreme** [GJena/gjena.github.io#4]
For the home page, the image tiles are extremely huge and cause excessive scrolling.
Perhaps scaling down the sizes to include 3 tiles in a row may help. I suggest 3 in a row because there are a total of 9(=3*3) tiles.

As for when the screen is too thin (say below 766px) you may want to go for 2 images in a row.

**Comment by hXtreme** [comment]
This hasn't been addressed yet.

**Comment by GJena** [comment]
Desktop version has been updated, mobile version will stay the same. Thanks for your interest.
